## extra Decap Config

# - name: "testCP"
#   label: "تست"
#   folder: "content/testCP"
#   create: true
#   slug: "{{slug}}"
#   fields:
#     - { label: "عنوان", name: "title", widget: "string", required: true }
#     - { label: "پوستر", name: "thumbnail", widget: "image", required: false }
#     - { label: "خلاصه", name: "description", widget: "string", required: true }

#     - { label: "محتوا", name: "body", widget: "markdown", required: true }
