backend:
  name: github
  repo: <%= process.env.GITHUB_REPO %>
  base_url: <%= process.env.PUBLIC_SITE_URL %>
  auth_endpoint: /github-auth/auth

local_backend: true
# publish_mode: editorial_workflow
media_folder: /public/content
public_folder: /content
locale: <%= process.env.APP_LOCALE %>
collections:
  - name: "notes"
    label: "یادداشت"
    folder: "content/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string", required: true }
      - { label: "پوستر", name: "thumbnail", widget: "image", required: true }
      - {
          label: "خلاصه",
          name: "description",
          widget: "string",
          required: true,
        }

      - { label: "محتوا", name: "body", widget: "markdown", required: true }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }

      - {
          name: "category",
          label: "سرویس",
          widget: "relation",
          collection: "category",
          searchFields: ["name"],
          valueField: "name",
          displayFields: ["name"],
          required: true,
        }

      - { label: "بنر", name: "banner", widget: "boolean", default: false }
      - { label: "دیدگاه", name: "comment", widget: "boolean", default: true }

  - name: "page"
    label: "صفحه"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string", required: true }
      - { label: "پوستر", name: "thumbnail", widget: "image", required: false }
      - {
          label: "خلاصه",
          name: "description",
          widget: "string",
          required: true,
        }

      - { label: "محتوا", name: "body", widget: "markdown", required: true }
      - {
          label: "افزودن به منو",
          name: "menu",
          widget: "boolean",
          default: false,
          required: true,
        }

  - name: category
    label: دسته‌بندی‌
    folder: content/category/
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { name: "name", label: "نام", required: true }
      - { label: "پوستر", name: "thumbnail", widget: "image", required: true }
      - { label: "محتوا", name: "body", widget: "markdown", required: true }
