<template>
  <div>
    <h3>دیدگاه‌ها</h3>
    <CommentsGiscus
      repo="mehotkhan/totoro"
      term="به توتورو خوش آمدید :)"
      reactions-enabled="1"
      emit-metadata="0"
      repo-id="R_kgDOKK9Djw"
      category="General"
      category-id="DIC_kwDOKK9Dj84CY100"
      mapping="title"
      strict="0"
      reactionsenabled="1"
      theme="light"
      loading="lazy"
      input-position="top"
      lang="fa"
    />
  </div>
</template>
