name: Repo Sync

on:
  push:
    branches:
      - master

# on:
#   schedule: 
#   - cron: "*/15 * * * *" # every 15 minutes. set to whatever interval you like

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/github-sync@v2
        name: Sync repo to branch
        with:
          source_repo: "mehotkhan/totoro"
          source_branch: master
          destination_branch: "update"
          github_token: ${{ secrets.WORKFLOW_TOKEN }}

      - uses: repo-sync/pull-request@v2
        name: Create pull request
        with:
          source_branch: "update"
          destination_branch: master
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
